using DanoniEditor.Core.Export;
using DanoniEditor.Core.Models;
using DanoniEditor.Core.Tests.Editing;
using DanoniEditor.Core.Timing;

namespace DanoniEditor.Core.Tests;

/// <summary>「現在のタブをdosエクスポート」(DosExporter.ExportSingleTab、2026-08-22要望対応、合作用途)の
/// テスト。カレント難易度タブ1つだけを対象に、dos.txtのデータ行のみ(プロジェクト共通ヘッダー・
/// JSラッパー・difDataは含まない)を、呼び出し元が指定したサフィックス番号で出力することを検証する。</summary>
public class DosSingleTabExportTests
{
    private static ChartProject NewProject()
    {
        var repo = TestFixtures.Repository();
        var p = new ChartProject { ProjectName = "t", MusicTitle = "title" };

        var normal = DifficultyTab.CreateFor(repo.Get("5"), "Normal");
        normal.Lanes[0].Notes.Add(0);

        var hard = DifficultyTab.CreateFor(repo.Get("5"), "Hard");
        hard.Lanes[0].Notes.Add(TimingEngine.TicksPerBeat);

        p.Tabs.AddRange([normal, hard]);
        return p;
    }

    [Fact]
    public void ExportSingleTab_NoSuffix_EmitsUnsuffixedDataName()
    {
        var repo = TestFixtures.Repository();
        var p = NewProject();
        var text = new DosExporter(repo.Get).ExportSingleTab(p, p.Tabs[1], suffixNumber: null);

        Assert.Contains("left_data=", text);
        Assert.DoesNotContain("left2_data=", text);
    }

    [Fact]
    public void ExportSingleTab_WithSuffix_EmitsSuffixedDataName()
    {
        var repo = TestFixtures.Repository();
        var p = NewProject();
        var text = new DosExporter(repo.Get).ExportSingleTab(p, p.Tabs[1], suffixNumber: 3);

        Assert.Contains("left3_data=", text);
        Assert.DoesNotContain("left_data=", text);
    }

    [Fact]
    public void ExportSingleTab_DoesNotIncludeProjectHeadersOrJsWrapper()
    {
        var repo = TestFixtures.Repository();
        var p = NewProject();
        var text = new DosExporter(repo.Get).ExportSingleTab(p, p.Tabs[0], suffixNumber: null);

        Assert.DoesNotContain("musicTitle", text);
        Assert.DoesNotContain("difData", text);
        Assert.DoesNotContain("externalDosInit", text);
    }

    [Fact]
    public void ExportSingleTab_TabNotInProject_Throws()
    {
        var repo = TestFixtures.Repository();
        var p = NewProject();
        var foreignTab = DifficultyTab.CreateFor(repo.Get("5"), "Foreign");

        Assert.Throws<InvalidOperationException>(
            () => new DosExporter(repo.Get).ExportSingleTab(p, foreignTab, suffixNumber: null));
    }

    [Fact]
    public void ExportSingleTab_ExcludedFromDosExportTab_StillExports()
    {
        // 2026-08-02のdosロック(ExcludeFromDosExport)は通常のExport(全タブ出力)向けの機能であり、
        // 単体タブ出力はユーザーが明示的に選んだタブをそのまま出力する機能のため、
        // ロック状態に関わらず出力できるべき。
        var repo = TestFixtures.Repository();
        var p = NewProject();
        p.Tabs[0].ExcludeFromDosExport = true;

        var text = new DosExporter(repo.Get).ExportSingleTab(p, p.Tabs[0], suffixNumber: null);
        Assert.Contains("left_data=", text);
    }

    [Fact]
    public void ExportSingleTab_LinkedSpeedEvents_IncludesAutoGeneratedIntermediatePoints()
    {
        // 2026-08-22に他の出力先(SKB/FUJI)で発覚した「始点終点オートスムージング出力」漏れと
        // 同種の不具合を作り込まないための回帰テスト。共通抽出元のAppendValueEvents経由で
        // ValueEventSmoothing.ExpandLinkedEventsが適用されることを確認する。
        var repo = TestFixtures.Repository();
        var p = NewProject();
        var tab = p.Tabs[0];
        long beat = TimingEngine.TicksPerBeat;
        tab.SpeedEvents.Add(new ValueEvent(0, 1.0, LinkGridDivision: 4));
        tab.SpeedEvents.Add(new ValueEvent(beat * 4, 2.0));

        var text = new DosExporter(repo.Get).ExportSingleTab(p, tab, suffixNumber: null);

        // 始点・終点・中間3点の計5件がカンマ区切り(frame,value)の10要素として出力されるはず。
        var line = text.Split('\n').Single(l => l.StartsWith("|speed_data="));
        var parts = line.Trim('|').Split('=')[1].Split(',');
        Assert.Equal(10, parts.Length);
    }
}
